"""init project

Revision ID: b2422974c9fb
Revises: 
Create Date: 2026-03-30 15:51:23.120846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2422974c9fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lvls',
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('required_xp', name='uq_lvls_required_xp'),
    sa.UniqueConstraint('value', name='uq_lvls_value')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('fio', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creator_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('creator_uuid', 'title', name='uq_projects_creator_title')
    )
    op.create_table('useractionlogs',
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_uuid', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('teams',
    sa.Column('project_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_by_uuid', sa.Uuid(), nullable=True),
    sa.Column('lead_uuid', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_uuid'], ['projects.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('project_uuid', 'name', name='uq_teams_project_name')
    )
    op.create_table('tasks',
    sa.Column('team_uuid', sa.Uuid(), nullable=False),
    sa.Column('issuer_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('assignee_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_WORK', 'ON_CHECK', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_for_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issuer_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_uuid'], ['teams.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('teammembers',
    sa.Column('team_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('added_by_uuid', sa.Uuid(), nullable=True),
    sa.Column('lvl_uuid', sa.Uuid(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lvl_uuid'], ['lvls.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_uuid'], ['teams.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('team_uuid', 'user_uuid', name='uq_team_members_team_user')
    )
    op.create_table('xpaccruallogs',
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('recipient_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('issuer_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('task_uuid', sa.Uuid(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_uuid'], ['tasks.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xpaccruallogs')
    op.drop_table('teammembers')
    op.drop_table('tasks')
    op.drop_table('teams')
    op.drop_table('useractionlogs')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('lvls')
    # ### end Alembic commands ###
