"""add notifications

Revision ID: 3d6163917539
Revises: b2422974c9fb
Create Date: 2026-03-31 16:28:35.083229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6163917539'
down_revision: Union[str, Sequence[str], None] = 'b2422974c9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('notifications',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('recipient_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('sender_user_uuid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
