from jose.constants import ALGORITHMS


DEFAULT_PASSWORD_HASH_ALGORITHM = ALGORITHMS.HS256

ARGON2_MEMORY_COST: int = 102_400
ARGON2_TIME_COST: int = 2
ARGON2_PARALLELISM: int = 8

PASSWORD_HASH_SCHEMES: list[str] = ["argon2"]
PASSWORD_HASH_DEPRECATED: str = "auto"
